FROM maven:3.9.0-eclipse-temurin-17 AS build

#If /app doesn't exist yet, Docker creates it automatically.
#If /app already exists (e.g., from a previous WORKDIR or from a COPY instruction that made the directory), Docker just #switches to it

WORKDIR /app

# Clone your GitHub repo (replace with your repo URL)
RUN git clone https://github.com/sitasrikanth/sita-devops.git sita-devops

# Optionally checkout a branch or tag
# RUN git checkout main

WORKDIR /app/sita-devops/docker-tomcat-app


RUN mvn clean install
FROM tomcat:latest
COPY --from=build /app/sita-devops/docker-tomcat-app/target/app.war /usr/local/tomcat/webapps
EXPOSE 8080
CMD ["catalina.sh", "run"]

